apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app: url-shortener
spec:
  refreshInterval: "1h" # כל כמה זמן לבדוק אם הסוד השתנה ב-AWS
  secretStoreRef:
    name: aws-secrets-manager # מצביע להגדרת החיבור שלנו מול AWS
    kind: ClusterSecretStore
  target:
    name: db-credentials # השם של ה-Secret המקומי שיווצר בקלאסטר
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD # המפתח שיופיע בסוד המקומי
      remoteRef:
        key: url-shortener/db-credentials # השם המדויק של הסוד ב-AWS
        property: password # המפתח בתוך ה-JSON ב-AWS