environment: staging
replicaCount: 2

image:
  repository: 066380525112.dkr.ecr.us-east-1.amazonaws.com/url-shortener
  tag: "1af5a8662d3ffac256f9f578010e3d43cdadebab"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"