environment: production
replicaCount: 5 # בפרודקשן אנחנו צריכים זמינות גבוהה יותר

image:
  repository: 066380525112.dkr.ecr.us-east-1.amazonaws.com/url-shortener
  tag: "latest" 
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests: # משאבים גבוהים יותר לסביבת ייצור
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"