apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: url-shortener-db-secret
  namespace: url-shortener
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: db-secret-local
  data:
  - secretKey: DB_PASSWORD
    remoteRef:
      key: url-shortener/db-secret
      property: DB_PASSWORD